### ISSUE TITLE
要望:デュアルモノ音声の分離をサポートしてほしい

### ISSUE THREAD

**Issue by monyone** [xtne6f/tsreadex#2]
aribb24.js への ID3 Timed Metadata の挿入対応など、大変にお手数をおかけしたと思います。
このような素晴らしいソフトウェアを作ってくださり、本当にありがとうございます。

更なる要望となってしまい申し訳ありませんが、要望致します。

## 背景

今現在の ffmpeg ベースの実装では、デュアルモノの判定と分離を自動で行わないため、
そのまま流す場合に、主音声に 主/副 が L/R にマッピングされた状態で送出されてしまいます。

ライブ視聴ではエンコーダを再起動しないと反映されず、視聴体験が悪くなってしまっています。
VOD視聴でもエンコーダのパラメータを外部のメタデータで変更する必要があり、複雑さが増してしまっています。

## 要望

デュアルモノ音声だった場合に、主音声 を 第1音声, 副音声 を 第2音声 へ分離して、送出できないでしょうか?

背景で述べた問題が、デュアルモノの第1音声,第2音声の分離で解決すると考えています。
また、モノラル音声をステレオ化できると、ffmpeg への音声チャンネルの固定ができると考えています。

### デュアルモノの判定方法について

外部のメタデータに依存せずにデュアルモノと判別できると考えています。

音声PES の ADTS ヘッダーにある `channel_configuration` が 0 だった場合にデュアルモノと判定可能だと思っています。
STD-B32 では この時に 2/1, 2/2, デュアルモノが送出され得ますが、EPG での運用ではデュアルモノしかありません。
この時だけ、デュアルモノと判定して分離できればと思っています。

### デュアルモノの分離方法について

デュアルモノである場合には、`SCE1(主)`, `SCE2(副)`, `TERM` という順番で AAC のデータが入ります。
このため 第1音声, 第2音声 の ADTS ヘッダの `channel_configuration` を 1 (モノラル) と変えて、
第1音声を `SCE1(主)`, `TERM`, 第2音声を `SCE2(副)`, `TERM` と分割する事で、デュアルモノを分離できます。
(`PCE` が不定期に入るため、このパースも行う必要があります...)

この方法は無劣化でデュアルモノを分離する amatsukaze の方法と同じです。
(amatsukaze は AACデコーダのライブラリを利用して、この判定を行っています)

### モノラル音声のステレオ化について

分離したデュアルモノ、モノラル音声の場合は `SCE`, `TERM` という順番で AAC のデータが入ります。
`SCE` は `|element_instance_tag|individual_channel_stream(0)|` という内容になっています。
この `SCE` を少しいじるだけで、ステレオ音声の `CPE` の内容にすることができます。

ステレオ音声の `CPE` で `common_window = 0` とした場合の内容は
`|element_instance_tag|0|individual_channel_stream(0)|individual_channel_stream(0)|` と構成されます。
この両方の `individual_channel_stream(0)` に SCE の `individual_channel_stream(0)` を入れるとステレオ化できます。

ffmpeg を使う際にモノラルから始まると、それ以降が全部モノラルになってしまうので、
モノラルの場合 ( `channel_configuration` = 0, 1) はステレオ化して頂けると扱いやすくなります。
(ステレオの場合は `channel_configuration` を 2 にします)

## 試験実装

一応、自分が慣れている node.js でデュアルモノ判定と分離の自前の実装を用意いたしました。
[node-aac-dualmono-splitter](https://github.com/monyone/node-aac-dualmono-splitter)
何か参考になればと思います。

概ね、このような AAC パース機能を tsreadex に入れる要望になると思っています。
この実装がやっている事は AAC の規格通りにパースして、`SCE` のデータを分離するというものです。

**Comment by xtne6f** [comment]
ありがとうございます。
あの規格書を解釈して実装までもっていく能力に感服します。
[node-aac-dualmono-splitter](https://github.com/monyone/node-aac-dualmono-splitter) 非常に参考になりました。

もうほとんど移植みたいな形ですが、ひととおり対応しました。
安定までいくらか修正は入ると予想しますが 4850e3b7a1fc9448759d91824f38a3c7ba7cf61c のようになりました。

**Comment by monyone** [comment]
すいません、見逃していて返答が遅れてしまいました。
一夜漬けで非常に拙いソースコードでしたが、参考にしていただき、開発が加速したようで何よりです。

こちらでも確認やバグ報告ができればと思います。
(Mirakurun を立ててたサーバが壊れてしまったので、そこの復旧からですね...)

**Comment by monyone** [comment]
一応、デュアルモノの音声の分離は、テスト素材でこちらでも確認できました!
ただ、こちらでは継続的なライブでの確認が難しいため、別途テストしていただく必要があるかと存じます。

正式リリースまでこのイシュー閉じなくてもいいかな? とは思っていますが
要望自体はこのコミットで叶えており、現時点でも閉じてもらって大丈夫です

**Comment by xtne6f** [comment]
こちらも一定期間テストを済ませたため、リリースとしました。
ありがとうございました。
